## Creating Numpy Object

In [1]:
import numpy as np 

## Creating List

list having different data types

In [2]:
data1 = [6, 7.5, 8, 0, 1, 'j','Joyce']

printing list

In [3]:
data1

[6, 7.5, 8, 0, 1, 'j', 'Joyce']

In [4]:
print(data1)

[6, 7.5, 8, 0, 1, 'j', 'Joyce']


printing datatype of list

In [5]:
type(data1)

list

printing last four elements from list

In [6]:
data1[1:4]

[7.5, 8, 0]

In [7]:
data1[-4:]

[0, 1, 'j', 'Joyce']

## Converting list to array

In [8]:
arr1=np.array(data1)

In [9]:
print(arr1)

['6' '7.5' '8' '0' '1' 'j' 'Joyce']


finding type and dimensions of array

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.ndim

1

## Creating ndarrays

In [12]:
data=[[1,2,3,4,11],[5,6,7,8,9]]

In [13]:
data

[[1, 2, 3, 4, 11], [5, 6, 7, 8, 9]]

In [14]:
type(data)

list

In [15]:
data[0]

[1, 2, 3, 4, 11]

In [16]:
data[1]

[5, 6, 7, 8, 9]

In [17]:
data[0][1]

2

In [18]:
arr2=np.array(data)

In [19]:
print(arr2)

[[ 1  2  3  4 11]
 [ 5  6  7  8  9]]


In [20]:
arr2.ndim

2

finding the rows and columns of array

In [21]:
arr2.shape

(2, 5)

In [22]:
arr2.dtype

dtype('int64')

In [23]:
data1 = [6, 7.5, 8, 0, 1, 'j','Joyce']

In [24]:
arr3=np.array(data1)

In [25]:
print(arr3)

['6' '7.5' '8' '0' '1' 'j' 'Joyce']


Setting default values for array

In [26]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [27]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

## empty creates an array without initializing its values to any particular value

In [42]:
nb=np.empty((2,3,4))

In [43]:
nb

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [30]:
nb[0]

array([[  6.91399767e-310,   1.55847356e-316,   6.91399787e-310,
          6.91398947e-310],
       [  6.91399783e-310,   6.91398947e-310,   6.91399787e-310,
          6.91399450e-310],
       [  6.91399783e-310,   6.91399450e-310,   6.91399787e-310,
          6.91398948e-310]])

In [31]:
nb[0]=[range(0,4),range(4,8),range(9,13)]

In [32]:
nb

array([[[  0.00000000e+000,   1.00000000e+000,   2.00000000e+000,
           3.00000000e+000],
        [  4.00000000e+000,   5.00000000e+000,   6.00000000e+000,
           7.00000000e+000],
        [  9.00000000e+000,   1.00000000e+001,   1.10000000e+001,
           1.20000000e+001]],

       [[  6.91399783e-310,   6.91398948e-310,   6.91399787e-310,
           6.91398947e-310],
        [  6.91399783e-310,   6.91398947e-310,   6.91399787e-310,
           6.91398949e-310],
        [  6.91399783e-310,   6.91398948e-310,   6.91399787e-310,
           6.91398948e-310]]])

In [33]:
nb[1]

array([[  6.91399783e-310,   6.91398948e-310,   6.91399787e-310,
          6.91398947e-310],
       [  6.91399783e-310,   6.91398947e-310,   6.91399787e-310,
          6.91398949e-310],
       [  6.91399783e-310,   6.91398948e-310,   6.91399787e-310,
          6.91398948e-310]])

In [34]:
nb[1]=range(8,12)

In [35]:
nb[1]

array([[  8.,   9.,  10.,  11.],
       [  8.,   9.,  10.,  11.],
       [  8.,   9.,  10.,  11.]])

In [36]:
nb[0][0]

array([ 0.,  1.,  2.,  3.])

In [37]:
nb[0][2][3]

12.0

In [39]:
nb[0][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

Displaying range of elements in array

In [ ]:
arr4=np.arange(5)

In [ ]:
arr4

## Data types for ndarrays(dtype)

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float)

In [ ]:
arr1

In [ ]:
arr1.dtype

In [ ]:
arr2=np.array([1,2,3],dtype=np.int)

In [ ]:
arr2

In [ ]:
arr2.dtype

## Type Casting for datatypes in ndarrays(astype)

In [ ]:
arr5=np.array([1,2,3,4,5])

In [ ]:
arr5

In [ ]:
arr5.dtype

In [ ]:
float_arr5=arr5.astype(np.float)

In [ ]:
float_arr5.dtype

In [ ]:
float_arr5

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [ ]:
arr

In [ ]:
arr.dtype

In [ ]:
int_arr=arr.astype(np.int64)

In [ ]:
int_arr.dtype

In [ ]:
int_arr

## Using another array’s dtype attribute

In [ ]:
int_array = np.arange(10)

In [ ]:
calibers = np.array([22, 270.89, 357, 380, 44.7, 50], dtype=np.float)

In [ ]:
int_array

In [ ]:
calibers

In [ ]:
int_array.dtype

In [ ]:
calibers.dtype

In [ ]:
int_array.astype(calibers.dtype)

In [ ]:
calibers.astype(int_array.dtype)

## Operations between Arrays and Scalars

Arrays are important because they enable you to express batch operations on data
without writing any for loops. This is usually called vectorization. Any arithmetic op-
erations between equal-size arrays applies the operation elementwise:

In [ ]:
data4=([1., 2., 3.], [4., 5., 6.])

In [ ]:
arr4=np.array(data4)

In [ ]:
arr4

In [ ]:
arr4=np.array([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
arr4

In [ ]:
arr4*arr4

In [ ]:
arr4+arr4

In [ ]:
arr4-arr4

In [ ]:
1/arr4

In [ ]:
arr4*0.99

In [ ]:
arr6=np.array([7,0.99,5.6])

In [ ]:
arr4+arr6

In [ ]:
arr4[0][1]*arr4[1][0]

## Basic Indexing and Slicing

In [ ]:
arr7=np.arange(10)

In [ ]:
arr7

In [ ]:
arr7[4]

In [ ]:
arr7[4:8]

Assign a scalar value to a slice, that particulaur value is
propagated (or broadcasted) to the entire selection

In [ ]:
arr7[4:8]=12

In [ ]:
arr7

In [ ]:
arr7_slice=arr7[4:8]

In [ ]:
arr7_slice

In [ ]:
arr7_slice[1]=12345

In [ ]:
arr7

In [ ]:
arr7_slice[2]=10

In [ ]:
arr7

In [ ]:
arr7[5:]=65

In [ ]:
arr7

In [ ]:
arr7_slice[:]=40

In [ ]:
arr7_slice

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr2d

In [ ]:
arr2d.dtype

In [ ]:
float_arr2d=arr2d.astype(np.float)

In [ ]:
arr2d.dtype

In [ ]:
float_arr2d

In [ ]:
arr2d[2]

In [ ]:
arr2d[2,0]

In [ ]:
arr2d[2][0]

In [ ]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
arr3

In [ ]:
arr3[0]

## Copying values to specific location in ndarrays(copy()) & retriving old values back

In [ ]:
arr_d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [ ]:
arr_d

In [ ]:
old_val=arr_d[0].copy()

In [ ]:
arr_d[0]=111

In [ ]:
arr_d

In [ ]:
arr_d[0]=old_val

In [ ]:
arr_d

## Indexing with slices

In [ ]:
arr_d

In [ ]:
arr_d[:2]

First value for row & second value for column

In [ ]:
arr_d[2,1:]

In [ ]:
arr_d[:,:1]

In [ ]:
arr_d[:2,1:]

In [ ]:
arr_d[2,-1]

In [ ]:
arr_d[:,:1]

## Boolean Indexing

In [ ]:
names = np.array(['Bob', 'Joe', 'Will','Bob', 'Will', 'Joe', 'Joe'])

In [ ]:
print(names)

In [ ]:
data=np.random.randn(7,4)

In [ ]:
data

In [ ]:
names=='Bob'

In [ ]:
data[names=='Bob']

In [ ]:
names!='Bob'

In [ ]:
data[(names!="Bob")]

In [ ]:
data[names!='Joe']=6

In [ ]:
data

In [ ]:
arr12=np.arange(32).reshape((8,4))

In [ ]:
arr12

## range() gives list while arange() gives array

In [ ]:
range(8)

In [ ]:
np.arange(8)

## reshape() function arranges the array elements in appropriate order of rows & columns

In [ ]:
arr13=np.arange(15).reshape((5,3))

In [ ]:
arr13

## transpose() (denoted by T) is used for matrix transpose

In [ ]:
arr13.transpose()

In [ ]:
arr13.T

In [ ]:
r_arr=np.random.randn(5,4)

In [ ]:
r_arr

## dot() function is used to perform matrix multiplication

In [ ]:
np.dot(arr13.T,r_arr)

In [ ]:
arr14=np.arange(16).reshape((2,2,4))

In [ ]:
arr14

In [ ]:
arr14.transpose()

In [ ]:
arr16=np.arange(4).reshape(2,2)

In [ ]:
arr16

In [ ]:
arr16.T

## Universal Functions: Fast Element-wise Array Functions

A universal function, or ufunc, is a function that performs elementwise operations on
data in ndarrays.

In [ ]:
arr16=np.arange(10)

In [ ]:
arr16

In [ ]:
sqrt_arr=np.sqrt(arr16)

In [ ]:
sqrt_arr

In [ ]:
exp_arr=np.exp(arr16)

In [ ]:
exp_arr

In [ ]:
arr17=np.random.randn(8)

In [ ]:
arr18=np.random.randn(8)

In [ ]:
arr17

In [ ]:
arr18

## maximum() function is used to find maximum elementwise value between two arrays. 

In [ ]:
max_arr=np.maximum(arr17,arr18)

In [ ]:
max_arr

## add() function is used to perform addton of values from array

In [ ]:
add_arr=np.add(arr17,arr18)

In [ ]:
add_arr

In [ ]:
arr19=np.random.randn(7)

In [ ]:
arr19

In [ ]:
mul=arr19*5

In [ ]:
mul

## modf() functionreturns the fractional and integral parts of a floating point array


In [ ]:
modf_arr=np.modf(mul)

In [ ]:
modf_arr

In [ ]:
arr20=np.random.randn(7)

In [ ]:
arr20

In [ ]:
abs_arr=np.abs(arr20)

In [ ]:
abs_arr