#### List Recap 
* Powerful
* Collection of values
* Holds different types
* Change, Add, Remove

* Need For Data Science Is :
    * Mathematical Operations over a Collection
    * Speed

In [35]:
# illustration 

height = [1.23,3.26,4.1,2.2]

In [36]:
height

[1.23, 3.26, 4.1, 2.2]

In [37]:
weight = [42.03,56.2,72.0,65.45]

In [38]:
weight

[42.03, 56.2, 72.0, 65.45]

In [39]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

#### Solution : NumPy
* Numeric python
* Alternative to python list : NumPy array
* Calculation over entire array
* Easy and Fast

In [40]:
import numpy as np

In [41]:
np_height = np.array(height)

In [42]:
np_height

array([ 1.23,  3.26,  4.1 ,  2.2 ])

In [43]:
np_weight = np.array(weight)

In [44]:
np_weight

array([ 42.03,  56.2 ,  72.  ,  65.45])

In [45]:
bmi = np_weight/ np_height **2

In [46]:
bmi

array([ 27.78108269,   5.28811773,   4.28316478,  13.52272727])

#### NumPy Remarks
* Numpy contains only element of same type
* Numpy comes with its own methods which behaves differently 

In [47]:
# Numpy contains only element of same type

np.array([1.23,"is",True])

# Output : All get converted into string

array(['1.23', 'is', 'True'], 
      dtype='<U32')

In [48]:
# Numpy comes with its own methods which behaves differently 

python_list = [1,2,3]

np_array = np.array([1,2,3])

In [49]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [50]:
np_array +np_array

array([2, 4, 6])

#### NumPy Subnetting
* Works same as Python list to get elements from the array

In [51]:
bmi

array([ 27.78108269,   5.28811773,   4.28316478,  13.52272727])

In [52]:
# Get the bmi for the second person 
bmi[1]

5.2881177311904857

In [53]:
# Get bmi above 20
bmi >20

array([ True, False, False, False], dtype=bool)

In [54]:
# Get bmi above 20
bmi[bmi> 20]

array([ 27.78108269])

## Lets Practice !!!

##### Excercise 1.1:
* Import the numpy package as np, so that you can refer to numpy with np.
* Use np.array() to create a numpy array from baseball. Name this array np_baseball.
* Print out the type of np_baseball to check that you got it right.

Code Snippet :
    # Create list baseball
    baseball = [180, 215, 210, 210, 188, 176, 209, 200]

    #Import the numpy package as np

    #Create a numpy array from baseball: np_baseball

    #Print out type of np_baseball

 

In [55]:
## Solution 

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


##### Excercise 1.2:
* Create a numpy array from height. Name this new array np_height.
* Print np_height.
* Multiply np_height with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.
* Print out np_height_m and check if the output makes sense.

Code Snippet :
    # height 
    height = [74, 74, 72,75, 75, 73]

    #Import numpy
    import numpy as np

    #Create a numpy array from height: np_height

    #Print out np_height

    #Convert np_height to m: np_height_m

    #Print np_height_m

Source : [stat.ucla.edu](http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights)

In [56]:
## Solution 

# height 
height = [74, 74, 72,75, 75, 73]

# Import numpy
import numpy as np

# Create a numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254 

# Print np_height_m
print(np_height_m)

[74 74 72 75 75 73]
[ 1.8796  1.8796  1.8288  1.905   1.905   1.8542]


##### Excercise 1.3:
* Create a numpy array from the weight list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as np_weight_kg.
* Use np_height_m and np_weight_kg to calculate the BMI of each player. Use the following equation:
* Save the resulting numpy array as bmi.
* Print out bmi

Code Snippet :
    # height in Inches
    height = [74, 74, 72,75, 75, 73]
    #weight in ponds
    weight = [180,215,210,195,203,220]

    #Import numpy
    import numpy as np

    #Create array from height with correct units: np_height_m
    np_height_m = np.array(height) * 0.0254

    #Create array from weight with correct units: np_weight_kg

    #Calculate the BMI: bmi

    #Print out bmi


Source : [stat.ucla.edu](http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights)

In [57]:
## Solution 

# height in Inches 
height = [74, 74, 72,75, 75, 73]

#weight in ponds
weight = [180,215,210,195,203,220]

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg/ np_height_m **2

# Print out bmi
print(bmi)

[ 23.11037639  27.60406069  28.48080465  24.37305888  25.37297924
  29.02517946]


##### Excercise 1.4:
* Create a boolean numpy array: the element of the array should be True if the corresponding baseball player's BMI is below 24. You can use the < operator for this. Name the array light.
* Print the array light.
* Print out a numpy array with the BMIs of all baseball players whose BMI is below 24. Use light inside square brackets to do a selection on the bmi array.

Code Snippet :
    # height in Inches
    height = [74, 74, 72,75, 75, 73]
    #weight in ponds
    weight = [180,215,210,195,203,220]

    #Import numpy
    import numpy as np

    #Calculate the BMI: bmi
    np_height_m = np.array(height) * 0.0254
    np_weight_kg = np.array(weight) * 0.453592
    bmi = np_weight_kg / np_height_m ** 2

    #Create the light array

    #Print out light
    
    #Print out BMIs of all baseball players whose BMI is below 21


Source : [stat.ucla.edu](http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights)

In [59]:
## Solution 

# height in Inches
height = [74, 74, 72,75, 75, 73]
#weight in ponds
weight = [180,215,210,195,203,220]

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 24

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[ True False False False False False]
[ 23.11037639]


##### Excercise 1.5:
* Subset np_weight: print out the element at index 5.
* Print out a sub-array of np_height: It contains the elements at index 1 up to and including index 4

Code Snippet :
    # height in Inches
    height = [74, 74, 72,75, 75, 73]
    #weight in ponds
    weight = [180,215,210,195,203,220]

    #Import numpy
    import numpy as np

    #Store weight and height lists as numpy arrays
    np_weight = np.array(weight)
    np_height = np.array(height)

    #Print out the weight at index 5

    #Print out sub-array of np_height: index 1 up to and including index 4



In [60]:
## Solution 

# height in Inches
height = [74, 74, 72,75, 75, 73]
#weight in ponds
weight = [180,215,210,195,203,220]

#Import numpy
import numpy as np

#Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

#Print out the weight at index 5
print(np_weight[5])

#Print out sub-array of np_height: index 1 up to and including index 4
print(np_height[1:4])

220
[74 72 75]


#### 2D NumPy Arrays
* ndarray stands for N Dimensional Array 
* Single type

In [71]:
import numpy as np 

height = [1.23,3.26,4.1,2.2]

np_height = np.array(height)

print(type(np_height))

<class 'numpy.ndarray'>


In [72]:
# creating 2D array

np_2d = np.array([[1.23,3.26,4.1,2.2],[52,45.2,65.12,78.25]])

In [73]:
np_2d

array([[  1.23,   3.26,   4.1 ,   2.2 ],
       [ 52.  ,  45.2 ,  65.12,  78.25]])

In [74]:
# Shape (2,4) ie 2 rows and 4 columns
np_2d.shape

(2, 4)

In [75]:
# to get all element in first row
np_2d[0]

array([ 1.23,  3.26,  4.1 ,  2.2 ])

In [77]:
# To get second element of row 1
np_2d[0][1]

3.2599999999999998

In [78]:
# this can also be done as 
np_2d[0,1]

3.2599999999999998

In [80]:
# If you want the second and third height and weight

np_2d[:,1:3]

array([[  3.26,   4.1 ],
       [ 45.2 ,  65.12]])

In [81]:
# get the weight of all family members
np_2d[1, :]

array([ 52.  ,  45.2 ,  65.12,  78.25])

##### Excercise 1.6:
* Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.
* Print out the type of np_baseball.
* Print out the shape attribute of np_baseball. Use np_baseball.shape.

Code Snippet :
    # Create baseball, a list of lists
    baseball = [[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]]

    #Import numpy
    import numpy as np

    #Create a 2D numpy array from baseball: np_baseball

    #Print out the type of np_baseball

    #Print out the shape of np_baseball


In [82]:
## Solution 

# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)


<class 'numpy.ndarray'>
(4, 2)


##### Excercise 1.7:
* Print out the 50th row of np_baseball.
* Make a new variable, np_weight, containing the entire second column of np_baseball.
* Select the height (first column) of the 124th baseball player in np_baseball and print it out.

Code Snippet :
    # Create baseball, a list of lists
    baseball = [[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]]

    #Import numpy package
    import numpy as np

    #Create np_baseball (2 cols)
    np_baseball = np.array(baseball)

    #Print out the 5th row of np_baseball

    #Select the entire second column of np_baseball: np_weight

    #Print out height of 3rd player


In [88]:
## Solution 

# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

#Import numpy package
import numpy as np

#Create np_baseball (2 cols)
np_baseball = np.array(baseball)

#Print out the 2th row of np_baseball
print(np_baseball[1,:])

#Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,1]

#Print out height of 3rd player
print(np_baseball[2,0])


[ 215.   102.7]
210.0


##### Excercise 1.8:
* You want to convert the units of height and weight. As a first step, create a numpy array with three values: 0.0254 and 0.453592. Name this array conversion.
* Multiply np_baseball with conversion and print out the result..

Code Snippet :
    # Create baseball, a list of lists
    baseball = [[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]]

    #Import numpy package
    import numpy as np

    #Create np_baseball (2 cols)
    np_baseball = np.array(baseball)
        
    #Create numpy array: conversion

    #Print out product of np_baseball and conversion
  


In [90]:
## Solution 

 # Create baseball, a list of lists
baseball = [[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]]

#Import numpy package
import numpy as np

#Create np_baseball (2 cols)
np_baseball = np.array(baseball)
        
#Create numpy array: conversion
conversion = np.array([ 0.0254, 0.453592])

#Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[  4.572      35.5616128]
 [  5.461      46.5838984]
 [  5.334      44.678812 ]
 [  4.7752     34.1101184]]


#### NumPy: Basic Statistics
* number crunching

In [98]:
import numpy as np
height_weight = [[5.5, 78.4],
                [8.5, 102.7],
                [7.7, 98.5],
                [8.6, 75.2]]

In [99]:
np_data = np.array(height_weight)
np_data

array([[   5.5,   78.4],
       [   8.5,  102.7],
       [   7.7,   98.5],
       [   8.6,   75.2]])

In [101]:
# Calculating Mean of heights
np.mean(np_data[:,0])

7.5749999999999993

In [102]:
# Calculating Median of heights
np.median(np_data[:,0])

8.0999999999999996

In [103]:
# Calculating Standard Divation
np.std(np_data[:,0])

1.2477479713467781

##### Excercise 1.9 :
* Create numpy array np_height that is equal to first column of np_baseball.
* Print out the mean of np_height.
* Print out the median of np_height.

Code Snippet :
    # np_baseball is available
    baseball = [[5.5, 78.4,23],
                [8.5, 102.7,30],
                [7.7, 98.5,28],
                [8.6, 75.2,26]]
                
    np_baseball = np.array(baseball)

    #Import numpy
    import numpy as np

    #Create np_height from np_baseball

    #Print out the mean of np_height

    #Print out the median of np_height 

In [104]:
## Solution 

# np_baseball is available
baseball = [[5.5, 78.4,23],
            [8.5, 102.7,30],
            [7.7, 98.5,28],
            [8.6, 75.2,26]]

np_baseball = np.array(baseball)

#Import numpy
import numpy as np

# Create np_height from np_baseball
np_height = np.array(np_baseball[:,0])

# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

7.575
8.1


##### Problem Defination :
* You've contacted FIFA for some data and they handed you two lists. The lists are the following: positions = ['GK', 'M', 'A', 'D', ...] heights = [191, 184, 185, 180, ...] Each element in the lists corresponds to a player. The first list, positions, contains strings representing each player's position. The possible positions are: 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense). The second list, heights, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).

* You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills.


##### Excercise 1.10 :
* Convert heights and positions, which are regular lists, to numpy arrays. Call them np_heights and np_positions.
* Extract all the heights of the goalkeepers. You can use a little trick here: use np_positions == 'GK' as an index for np_heights. Assign the result to gk_heights.
* Extract all the heights of all the other players. This time use np_positions != 'GK' as an index for np_heights. Assign the result to other_heights.
* Print out the median height of the goalkeepers using np.median(). Replace None with the correct code.
* Do the same for the other players. Print out their median height. Replace None with the correct code..

Code Snippet :
    #heights and positions are available as lists

    heights = [191, 184, 185, 180,210,203,185,192,201,189]
    positions = ['D', 'M', 'A', 'GK','GK', 'A','GK','M'] 
                
   
    #Import numpy
    import numpy as np

    #Convert positions and heights to numpy arrays: np_positions, np_heights


    #Heights of the goalkeepers: gk_heights

    #Heights of the other players: other_heights

    #Print out the median height of goalkeepers. Replace 'None'

In [108]:
## Solution 

#heights and positions are available as lists

heights = [191, 184, 185, 180,210,203,185,192,201,189]
positions = ['D', 'M', 'A', 'GK','GK', 'A','GK','M','GK','D'] 

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)


# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']
print(gk_heights)

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']
print(other_heights)

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

[180 210 185 201]
[191 184 185 203 192 189]
Median height of goalkeepers: 193.0
Median height of other players: 190.0
